blank_issues_enabled: false
contact_links:
  - name: Usage Question / Discussion
    url: https://github.com/MeetSohailCodes/CodexPlusPlus/discussions
    about: When unsure if it is a Bug, discuss it here first.

